### ISSUE TITLE
Unable to Treat recordings produced by Kaleidoscope if placed in daily/nightly Output Directories

### ISSUE THREAD

**Issue by Ewan-P** [YvesBas/Tadarida-L#6]
### Situation:
Using Kaleidoscope to generate short recordings as input to Tadarida-L.
Kaleidoscope can be configured to place output recordings into sub directories based on day or night of recording.  These sub directories are named using the following convention: YYYYMMDD e.g. 19870201 (January 1st, 1987).

When Treating these files with Tadaridia-L.exe the following warning box is displayed and processing halts.
Heading>"Unauthorised Treatment"
Message>"Folder in the database!"

This situation is repeatable and demonstrated as follows:
1. Create directory test_dir,
2. Create sub directories 20200101 and 20200102
3. Start Tadarida-L
4. Select test_dir as "wav files directory"
5. Deselect checkbox "da2 and jpg files"
6. Select checkbox "include subfolders"
7. Click "Treat" button

Result: above warning displayed.

The issue is specific to the naming structure of the directory names. This can be demonstrated following the above steps but changing the names of the sub directories to be 20200101x and 20200102x. 

### Relevant Code
TadardiaMainWindow.cpp, line 1147.
This line contains the test that raises the error message.

### Cause of problem:
Apparent clash of directory names between those used internally by Tadarida-L and those generated by Kaleidoscope.

### Suggested fix:
Adopt alternative naming convention for internal Tadarida-L directories.

### Workaround:
After processing with Kaleidoscope rename sub directories prior to Treatment with Tadarida-L.  
e.g. if OS = Linux 
> find . -type d -iname "*20??????" | xargs -I {} mv {} {}x

**Comment by rduivenvoorde** [comment]
Had a small debug session to see if I could reproduce your issue.
It appears that this method:
https://github.com/YvesBas/Tadarida-L/blob/master/sources/TadaridaMainWindow.cpp#L900
is testing for something I do not understand: "this method distinguishes folders of reference base from others" 
But it explicitly tests if folders have a 8 character long name with only numbers in it (ascii 48 till 57 are numbers 0 till 9 in asciitable)....
So yes, I agree: it would be better if there would be some naming scheme (like prepending base_... or so?)

**Comment by YvesBas** [comment]
The name testing is about the RSDB (references already labelled) and intends to avoid what I think you were about to do: mixing test files and reference files. The problem is that you selected a folder as a RSDB that contained already some folders and files, though it should be empty or containing previously labelled files with the correct structure. I think you should select an empty folder as a RSDB, and then treat (left panel) your Kaleidoscope outputs that can have any possible folder structure and names. When you'll label some calls within your files, they'll be automatically copied to the previously empty RSDB folder with every associated files (lables, features, spectrograms...)
I hope I'm clear enough, please refer to the manual that explains the process!
